# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'LAB3 Security Sandbox (Tenant)'
    subscriptionId: '551b785f-d46c-4496-803e-b3e5cc08adeb'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rlarmlinked-rg'
    location: 'Australia East'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/Robert-lintun/RL-ARMPipeline-repo/main/create_web_app/azuredeploy.json'
    overrideParameters: '-projectName rlarmcicd'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'